
# Open this file in vscode and use it with the rest-client plugin

POST http://localhost:32000/score HTTP/1.1
Content-Type: application/json

{
    "data": [{
    "Age": 20,
    "Sex": "male",
    "Job": 0,
    "Housing": "own",
    "Saving accounts": "little",
    "Checking account": "little",
    "Credit amount": 100,
    "Duration": 48,
    "Purpose": "radio/TV"
  }]
}