name: batch-scoring-env
channels:
  - conda-forge
  - defaults
dependencies:
  - python=3.6.2
  - pip:
    # Azure Machine Learning specific dependencies (do not change!)
    - azureml-defaults
    - azureml-core>=1.13.0
    - azureml-dataprep[pandas,fuse] # Required for parallel batch scoring (ParallelRunStep)
    # Replace those with your own dependencies (either from your Conda env or requirements.txt)
    - numpy==1.16.2
    - scikit-learn==0.20.3
    - scipy==1.2.1
    - pandas==0.25.3
    - joblib==0.13.2
    - inference-schema
